# Generated by Django 5.2.5 on 2025-08-15 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='ai_processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='ai_suggestions',
            field=models.JSONField(blank=True, default=list, help_text='Gemini AI suggestions'),
        ),
    ]
