# Generated by Django 5.2.5 on 2025-08-12 06:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContextEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('source_type', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'Email'), ('notes', 'Notes'), ('calendar', 'Calendar')], max_length=20)),
                ('sender', models.CharField(blank=True, max_length=100)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
                ('extracted_tasks', models.JSONField(blank=True, default=list)),
                ('key_topics', models.JSONField(blank=True, default=list)),
                ('urgency_level', models.CharField(default='medium', max_length=10)),
                ('sentiment', models.CharField(default='neutral', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Context Entries',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ProcessedInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insight_text', models.TextField()),
                ('suggested_action', models.CharField(blank=True, max_length=100)),
                ('priority_suggestion', models.CharField(blank=True, max_length=10)),
                ('deadline_suggestion', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('context_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='context.contextentry')),
            ],
        ),
    ]
