# Generated by Django 5.2.5 on 2025-08-15 07:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contextentry',
            options={'ordering': ['-created_at'], 'verbose_name': 'Context Entry', 'verbose_name_plural': 'Context Entries'},
        ),
        migrations.RemoveField(
            model_name='contextentry',
            name='extracted_tasks',
        ),
        migrations.RemoveField(
            model_name='contextentry',
            name='key_topics',
        ),
        migrations.RemoveField(
            model_name='contextentry',
            name='processed',
        ),
        migrations.RemoveField(
            model_name='contextentry',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='contextentry',
            name='sentiment',
        ),
        migrations.RemoveField(
            model_name='contextentry',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='contextentry',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='contextentry',
            name='urgency_level',
        ),
        migrations.AddField(
            model_name='contextentry',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Additional metadata'),
        ),
        migrations.AddField(
            model_name='contextentry',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contextentry',
            name='processed_insights',
            field=models.JSONField(blank=True, default=list, help_text='AI-generated insights and task suggestions'),
        ),
        migrations.AddField(
            model_name='contextentry',
            name='processing_status',
            field=models.CharField(choices=[('unprocessed', 'Unprocessed'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Failed')], default='unprocessed', max_length=20),
        ),
        migrations.AddField(
            model_name='contextentry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='contextentry',
            name='content',
            field=models.TextField(help_text='Context content from various sources', validators=[django.core.validators.MinLengthValidator(5)]),
        ),
        migrations.AlterField(
            model_name='contextentry',
            name='source_type',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'Email'), ('notes', 'Notes')], default='notes', max_length=20),
        ),
        migrations.DeleteModel(
            name='ProcessedInsight',
        ),
    ]
